# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
name: "SchemataLabs"
# run once in 24 hours or pull event to main
on:
  # push:
    # branches: [ main ]
  pull_request:    
    branches: [ main ]
  # schedule: 
    # - cron: "0 0 * * *" 
jobs:
  schemata-score:
    name: Schemata score
    runs-on: ubuntu-latest
    # permissions:
      # actions: read
      # contents: read
      # pull-requests: write
    
    steps:
      - name: Checkout PR repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v35
        with:
          files: |            
            *.yml
            **/*.yml

      - name: List all changed files
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo ${{ github.event.pull_request.head.repo.full_name }} + "$file was changed"
            echo $file
          done      


      #- name: get_modified_files
      #  id: diff
      #  working-directory: './diff_files'
      #  run: |


     
      #- name: Compute Schemata score
      #  run: |
      #    CODE=`curl --http1.1  --request GET --url 'https://03f9-2603-8080-1ef0-81f0-5024-8e6f-6a29-1618.ngrok.io/connect/v1/schema/table/score/domain/3?name=org.entities.Department' --header 'authorization: ${{ secrets.SCHEMATA_TOKEN }}' --header 'content-Type: application/json'`
      #    echo $CODE 
      #    if [ "$CODE"!="200" ];
      #    then
      #        echo "FAILURE"
      #        exit 500
      #    else
      #        echo "SUCCESS"
      #        exit 0
      #    fi
