# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
name: "SchemataLabs"
# run once in 24 hours or pull event to main
on:
  push:
    branches: [ main ]
  pull_request:    
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *" 
jobs:
  schemata-score:
    name: Schemata score
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      pull-requests: write
    # strategy:
    #  fail-fast: false #if set to true, GitHub will cancel all in-progress and queued jobs if any job in the matrix fails.
    steps:
      - name: Checkout current repository
        uses: actions/checkout@main
        with:
          ref: ${{ github.ref }} 
     
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'
